# Enable Split Keyboard functionality
CONFIG_ZMK_SPLIT=y

# Enable Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable Pointing / Trackball
CONFIG_ZMK_POINTING=y

# Enable RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# Go to sleep after 15 minutes (900,000 ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Force the new name
CONFIG_ZMK_KEYBOARD_NAME="CCK BALL"

# THE SECRET WEAPON: Force the keyboard to wipe its internal name cache on boot
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
